# Generated by Django 5.1.6 on 2025-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_teatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
